### PR TITLE
Add option necessary to tribits for single submission to cdash

### PR DESCRIPTION
**Pull request by bmpersc**
Apply change necessary to support a single submit for subprojects to be applied correctly. Without this change all the build information is applied to the last subproject listed in cdash instead of the correct package.

### CODE REVIEW

**Review by jwillenbring — APPROVED** [review]
This seems a good approach. It worked in testing.

**Comment by bmpersc** [comment]
Is there a reason the PR testing hasn't happened yet? I thought the autotester for this fork ran on a schedule.

**Comment by bmpersc** [comment]
This has now run to completion and did submit to testing-vm. The downside is that there was a non-related issue that caused a failure. On the positive side the jenkins job correctly reported failure. The negative is that the submission script reported that the build succeeded despite it failing.
output is:
Error(s) when building project
Build succeeded.
This is coming from the fact that the error code that we get from ctest is reporting 0 for every build regardless of what the actual build says it does.

**Review by jwillenbring — APPROVED** [review]
This small change looks good and was verified to work as expected.

**Pull request closed without merging**
