### PR TITLE
A file to enable packages for pull request testing

### PR DESCRIPTION
**Pull request by jwillenbring**
We want to enable less than all of Trilinos when possible for pull request testing. This is a oversimplified script to help us do that.

### CODE REVIEW

**Comment by jwillenbring** [comment]
Status Flag 'Pull Request Inspected' - Auto Inspected - Inspection Has Been Deemed Not Necessary for this Pull Request.

**Comment by jwillenbring** [comment]
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

JOB: Trilinos_autotester_test; Build 81 on Jenkins server at https://ascic-jenkins.sandia.gov
  Using Parameters:
  * COMPILER_MODULE = sems-gcc/4.8.4
  * JENKINS_BUILD_TYPE = Release
  * JENKINS_COMM_TYPE = MPI
  * JENKINS_DO_COMPLEX = OFF
  * JENKINS_JOB_TYPE = Experimental
  * MPI_MODULE = sems-openmpi/1.8.7
  * TEST_REPO_ALIAS = TRILINOS
  * TRILINOS_SOURCE_BRANCH = jwillenbring-patch-1
  * TRILINOS_SOURCE_REPO = https://github.com/jwillenbring/Trilinos
  * TRILINOS_SOURCE_SHA = 549c3e1afe14dae65d1905ad7da096c9c09fa030
  * TRILINOS_TARGET_BRANCH = develop
  * TRILINOS_TARGET_REPO = https://github.com/jwillenbring/Trilinos
  * TRILINOS_TARGET_SHA = f4122e775c43d77f972a0e88a70009aa0f1f5993

Using Repos:
Repo: TRILINOS (jwillenbring/Trilinos) Branch: jwillenbring-patch-1 SHA: [549c3e1afe14dae65d1905ad7da096c9c09fa030] - TEST_REPO

Pull Request Author: jwillenbring (James Willenbring)

**Comment by jwillenbring** [comment]
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

=== TESTING HAS PASSED ===

JOB: Trilinos_autotester_test Build 81 - PASSED:
-- JENKINS PARAMETERS:
   * COMPILER_MODULE = sems-gcc/4.8.4
   * JENKINS_BUILD_TYPE = Release
   * JENKINS_COMM_TYPE = MPI
   * JENKINS_DO_COMPLEX = OFF
   * JENKINS_JOB_TYPE = Experimental
   * MPI_MODULE = sems-openmpi/1.8.7
   * TEST_REPO_ALIAS = TRILINOS
   * TRILINOS_SOURCE_BRANCH = jwillenbring-patch-1
   * TRILINOS_SOURCE_REPO = https://github.com/jwillenbring/Trilinos
   * TRILINOS_SOURCE_SHA = 549c3e1afe14dae65d1905ad7da096c9c09fa030
   * TRILINOS_TARGET_BRANCH = develop
   * TRILINOS_TARGET_REPO = https://github.com/jwillenbring/Trilinos
   * TRILINOS_TARGET_SHA = f4122e775c43d77f972a0e88a70009aa0f1f5993

**Comment by jwillenbring** [comment]
Status Flag 'Pull Request Inspected' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

**Comment by jwillenbring** [comment]
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

**Comment by william76** [comment]
Arrrrrr!

**Pull request closed without merging**
